"""
gen_contract_c.py — nirdet_pp.c is GENERATED, not maintained
=============================================================
    python gen_contract_c.py --emit      # write nirdet_pp.c
    python gen_contract_c.py --check     # exit 1 if the file on disk is stale
    python gen_contract_c.py --print     # to stdout

WHY THIS EXISTS
---------------
Six decoders implement the NIRDet decode contract. Five of them `import
config`. nirdet_pp.c cannot, so until now it was kept in step by a grep test
(test_decode_contract T1) that could only prove FOUR #defines matched. It
could not prove that the DECODE BODY matched, and in fact it did not: the C
filtered degenerate boxes on the PRE-clamp extent and applied max_det as a
pre-NMS heap capacity. Both are contract violations that no test could see.

Parity is now BY CONSTRUCTION. The constants and the membership body are
rendered from config.py. `--check` is called by test_decode_contract T8, so a
config.py edit that is not followed by `--emit` fails the gate tests.

THE STAMP IS NOT deploy_contract()['hash']
------------------------------------------
deploy_contract() folds in CLAHE settings and a flat-field file digest, which
are DATASET properties: two profiles produce two different hashes for the same
C source. The stamp below covers only the frozen decode/membership constants,
which is exactly the set this file renders. Mixing the two would make
nirdet_pp.c churn on every profile change.

Pure stdlib plus `import config` (numpy). No torch, no new dependencies.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import os
import sys

import config as cfgmod

HERE = os.path.dirname(os.path.abspath(__file__))
C_PATH = os.path.join(HERE, "nirdet_pp.c")

BANNER = ("GENERATED BY gen_contract_c.py FROM config.py -- DO NOT EDIT. "
          "Run: python gen_contract_c.py --emit")


# ---------------------------------------------------------------------------
# the values this file is allowed to inject
# ---------------------------------------------------------------------------

def contract_values() -> dict:
    """The frozen decode + membership constants, straight from config.py."""
    return {
        "DECODE_OFFSET_SCALE": float(cfgmod.DECODE_OFFSET_SCALE),
        "DECODE_OFFSET_BIAS": float(cfgmod.DECODE_OFFSET_BIAS),
        "REG_LOG_CLAMP_MIN": float(cfgmod.REG_LOG_CLAMP_MIN),
        "REG_LOG_CLAMP_MAX": float(cfgmod.REG_LOG_CLAMP_MAX),
        "NIRDET_MIN_BOX_PX": float(cfgmod.MIN_BOX_PX),
        "NIRDET_NUM_CLASSES": int(cfgmod.NUM_CLASSES),
        "NIRDET_MAX_LEVELS": max(3, len(cfgmod.STRIDES)),
        "NIRDET_MAX_DET": int(cfgmod.NIRDET_MAX_DET),
        "PRE_NMS_TOPK": int(cfgmod.PRE_NMS_TOPK),
    }


def contract_stamp(vals: dict) -> str:
    """Deterministic 16-hex digest over the injected values only.

    No timestamp, no hostname, no path: two machines with the same config.py
    must produce byte-identical C, or --check is useless in CI.
    """
    blob = ";".join(f"{k}={vals[k]!r}" for k in sorted(vals))
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:16]


def _cf(v: float) -> str:
    """Render a float as a C float literal that round-trips exactly."""
    return f"{float(v)!r}f"


# ---------------------------------------------------------------------------
# the template
# ---------------------------------------------------------------------------
# Placeholders are @@NAME@@, not str.format braces: C is brace-dense and
# doubling every one of them is how a generator acquires its own bug class.

_TEMPLATE = r'''/*
 * nirdet_pp.c — NIRDet-Lite post-processor for STM32N6 / Cortex-M55
 * ==================================================================
 * @@BANNER@@
 *
 * Contract stamp: @@STAMP@@
 *
 * Consumes the INT8 NPU output (THREE blobs per level: cls 1ch, off 2ch,
 * size 2ch, each with its own scale / zero-point) and produces final person
 * boxes in canvas pixels. No dynamic allocation anywhere.
 *
 * THREE BLOBS, THREE SCALES
 * -------------------------
 * The head emits off and size as separate convolutions precisely so the
 * quantiser gives them independent scale / zero-point pairs: the offsets are
 * unbounded while the sizes are clamped to [REG_LOG_CLAMP_MIN,
 * REG_LOG_CLAMP_MAX], and a shared scale spanning both costs roughly twice
 * the box-width error per LSB.
 *
 * MIN-HEAP, NOT RASTER-ORDER TRUNCATION
 * -------------------------------------
 * Filling out[] in raster order and stopping at max_det discards every
 * candidate in the lower-right of the frame once the buffer fills — a
 * systematic spatial bias, and near-field pedestrians appear low in the
 * frame. This version keeps a fixed-capacity MIN-HEAP over the candidate
 * pool. The threshold test is done in the INTEGER domain (a per-level int8
 * threshold derived once), so the overwhelming majority of cells are
 * rejected with a single int8 compare and never touch the FPU.
 *
 * POST-DECODE (MEMBERSHIP) CONTRACT — canonical order, config.py:
 *   1. decode to cx, cy, w, h in canvas pixels
 *   2. convert to xyxy
 *   3. CLAMP xyxy to [0, img_w] x [0, img_h]
 *   4. DROP boxes whose CLAMPED extent is <= NIRDET_MIN_BOX_PX
 *   5. NMS
 *   6. truncate to cfg->max_det
 *
 * Steps 3/4 used to run in the opposite order here, and step 6 used to be
 * applied as the pre-NMS heap capacity. Both are fixed. Consequence for
 * callers: out_cap must now be >= NIRDET_MAX_DET, not >= cfg->max_det,
 * because NMS runs over the full candidate pool in out[] before truncation.
 *
 * Build the selftest with:
 *   cc -DNIRDET_PP_SELFTEST -O2 nirdet_pp.c -lm -o nirdet_pp_test && ./nirdet_pp_test
 */

#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>

/* ---------------------------------------------------------------------- *
 * DECODE CONTRACT — rendered from config.py. Edit config.py, then re-emit.
 * ---------------------------------------------------------------------- */
#define NIRDET_CONTRACT_STAMP "@@STAMP@@"

#define DECODE_OFFSET_SCALE  @@DECODE_OFFSET_SCALE@@
#define DECODE_OFFSET_BIAS   @@DECODE_OFFSET_BIAS@@
#define REG_LOG_CLAMP_MIN    @@REG_LOG_CLAMP_MIN@@
#define REG_LOG_CLAMP_MAX    @@REG_LOG_CLAMP_MAX@@
#define NIRDET_MIN_BOX_PX    @@NIRDET_MIN_BOX_PX@@

#define NIRDET_NUM_CLASSES   @@NIRDET_NUM_CLASSES@@
#define NIRDET_MAX_LEVELS    @@NIRDET_MAX_LEVELS@@
#define NIRDET_MAX_DET       @@NIRDET_MAX_DET@@

/* Make NIRDET_NUM_CLASSES load-bearing: it is checked by
 * test_decode_contract.py T1 but referenced by no C expression, so an
 * accidental change would otherwise compile silently while the single-class
 * decode path in nirdet_decode_level stays wrong. */
_Static_assert(NIRDET_NUM_CLASSES == 1,
    "this post-processor is single-class; update nirdet_decode_level "
    "to handle multiple classes before increasing NIRDET_NUM_CLASSES");
_Static_assert(NIRDET_MAX_LEVELS >= 1 && NIRDET_MAX_LEVELS <= 8,
    "NIRDET_MAX_LEVELS is a static capacity for NirdetCfg.levels[]");

/* ---------------------------------------------------------------------- */

typedef struct {
    float x1, y1, x2, y2;   /* canvas pixels */
    float score;            /* sigmoid(logit) */
} NirdetBox;

typedef struct {
    /* cls: 1 channel, off: 2 channels (t_cx, t_cy),
       size: 2 channels (t_w, t_h). Each blob is CHW int8. */
    const int8_t *cls;
    const int8_t *off;
    const int8_t *size;

    float cls_scale;   int32_t cls_zp;
    float off_scale;   int32_t off_zp;
    float size_scale;  int32_t size_zp;

    int32_t grid_h;
    int32_t grid_w;
    int32_t stride;
} NirdetLevelCfg;

typedef struct {
    NirdetLevelCfg levels[NIRDET_MAX_LEVELS];
    int32_t n_levels;        /* runtime, not compile-time */
    int32_t img_h;           /* canvas height */
    int32_t img_w;           /* canvas width  */
    float   score_thresh;    /* from the dataset profile */
    float   iou_thresh;
    int32_t max_det;         /* <= NIRDET_MAX_DET; applied AFTER NMS */
} NirdetCfg;

/* ---------------------------------------------------------------------- *
 * scalar helpers
 * ---------------------------------------------------------------------- */

static inline float nirdet_sigmoid(float x)
{
    /* Exact two-branch logistic, bit-comparable with config.np_sigmoid and
     * torch.sigmoid. Do NOT clamp the argument: clamping shifts every
     * decoded centre by up to DECODE_OFFSET_SCALE * eps * stride and is
     * invisible to a reference implementation that clamps too. */
    if (x >= 0.0f) {
        return 1.0f / (1.0f + expf(-x));
    }
    const float e = expf(x);
    return e / (1.0f + e);
}

static inline float nirdet_clampf(float v, float lo, float hi)
{
    return v < lo ? lo : (v > hi ? hi : v);
}

static inline float nirdet_deq(int8_t q, int32_t zp, float scale)
{
    return ((float)((int32_t)q - zp)) * scale;
}

/*
 * Integer-domain score gate.
 *   sigmoid(logit) >= t  <=>  logit >= logit(t)  <=>  q >= zp + logit(t)/scale
 * Computed ONCE per level; every cell is then a single int8 compare.
 */
static int32_t nirdet_int_thresh(float score_thresh, float scale, int32_t zp)
{
    float t = nirdet_clampf(score_thresh, 1e-6f, 1.0f - 1e-6f);
    float logit = logf(t / (1.0f - t));
    float q = (float)zp + logit / (scale > 0.f ? scale : 1e-9f);
    float c = ceilf(q);
    if (c < -128.f) c = -128.f;
    if (c >  127.f) c =  127.f;
    return (int32_t)c;
}

/* ---------------------------------------------------------------------- *
 * fixed-capacity min-heap on .score
 * ---------------------------------------------------------------------- */

static inline void heap_swap(NirdetBox *a, NirdetBox *b)
{
    NirdetBox t = *a; *a = *b; *b = t;
}

static inline void heap_sift_down(NirdetBox *h, int32_t n, int32_t i)
{
    for (;;) {
        int32_t l = 2 * i + 1, r = l + 1, m = i;
        if (l < n && h[l].score < h[m].score) m = l;
        if (r < n && h[r].score < h[m].score) m = r;
        if (m == i) return;
        heap_swap(&h[i], &h[m]);
        i = m;
    }
}

static inline void heap_sift_up(NirdetBox *h, int32_t i)
{
    while (i > 0) {
        int32_t p = (i - 1) / 2;
        if (h[p].score <= h[i].score) return;
        heap_swap(&h[p], &h[i]);
        i = p;
    }
}

static inline void heap_push(NirdetBox *h, int32_t *n, const NirdetBox *b)
{
    h[*n] = *b;
    heap_sift_up(h, *n);
    (*n)++;
}

static inline void heap_pop(NirdetBox *h, int32_t *n)
{
    if (*n <= 0) return;
    (*n)--;
    h[0] = h[*n];
    heap_sift_down(h, *n, 0);
}

/*
 * Offer a candidate to a capacity-limited heap.
 *   heap not full            -> push
 *   heap full, score > root  -> replace the weakest candidate
 *   heap full, score <= root -> discard
 * The frame's strongest candidates survive regardless of raster position.
 */
static inline void heap_offer(NirdetBox *h, int32_t *n, int32_t cap,
                              const NirdetBox *b)
{
    if (*n < cap) {
        heap_push(h, n, b);
    } else if (cap > 0 && b->score > h[0].score) {
        h[0] = *b;
        heap_sift_down(h, *n, 0);
    }
}

/* ---------------------------------------------------------------------- *
 * IoU + greedy NMS (no allocation)
 * ---------------------------------------------------------------------- */

static float nirdet_iou(const NirdetBox *a, const NirdetBox *b)
{
    float x1 = a->x1 > b->x1 ? a->x1 : b->x1;
    float y1 = a->y1 > b->y1 ? a->y1 : b->y1;
    float x2 = a->x2 < b->x2 ? a->x2 : b->x2;
    float y2 = a->y2 < b->y2 ? a->y2 : b->y2;
    float iw = x2 - x1, ih = y2 - y1;
    if (iw <= 0.f || ih <= 0.f) return 0.f;
    float inter = iw * ih;
    float aa = (a->x2 - a->x1) * (a->y2 - a->y1);
    float ab = (b->x2 - b->x1) * (b->y2 - b->y1);
    float uni = aa + ab - inter;
    return uni > 0.f ? inter / uni : 0.f;
}

/* Drain the min-heap back-to-front into out[]: each pop removes the SMALLEST
 * remaining entry, so the first pop lands in the last slot and the final pop
 * lands at out[0] — descending order in O(n log n), no extra buffer. */
static void nirdet_heap_drain_desc(NirdetBox *h, int32_t n, NirdetBox *out)
{
    int32_t i = n;
    while (i > 0) {
        NirdetBox top = h[0];
        heap_pop(h, &i);
        out[i] = top;
    }
}

/*
 * Greedy NMS over boxes ALREADY in descending score order.
 *
 * Step 5 of the membership contract only. It does NOT apply max_det: that is
 * step 6, applied by the caller AFTER suppression, so a cluster of mutually
 * suppressing duplicates cannot consume output slots.
 *
 * NOT REENTRANT: `suppressed` is a STATIC buffer. Serialise calls.
 */
static int32_t nirdet_nms(NirdetBox *boxes, int32_t n, float iou_thresh)
{
    static uint8_t suppressed[NIRDET_MAX_DET];
    if (n <= 0) return 0;
    if (n > NIRDET_MAX_DET) n = NIRDET_MAX_DET;
    memset(suppressed, 0, (size_t)n);

    int32_t kept = 0;
    for (int32_t i = 0; i < n; ++i) {
        if (suppressed[i]) continue;
        for (int32_t j = i + 1; j < n; ++j) {
            if (suppressed[j]) continue;
            if (nirdet_iou(&boxes[i], &boxes[j]) > iou_thresh)
                suppressed[j] = 1u;
        }
        boxes[kept++] = boxes[i];
    }
    return kept;
}

/* ---------------------------------------------------------------------- *
 * one level -> heap
 * ---------------------------------------------------------------------- */

static void nirdet_decode_level(const NirdetLevelCfg *lv, const NirdetCfg *cfg,
                                NirdetBox *heap, int32_t *heap_n, int32_t cap)
{
    const int32_t H = lv->grid_h, W = lv->grid_w;
    const int32_t plane = H * W;
    const int32_t q_thr = nirdet_int_thresh(cfg->score_thresh,
                                            lv->cls_scale, lv->cls_zp);
    const float img_w = (float)cfg->img_w;
    const float img_h = (float)cfg->img_h;
    const float st = (float)lv->stride;

    for (int32_t row = 0; row < H; ++row) {
        for (int32_t col = 0; col < W; ++col) {
            const int32_t i = row * W + col;
            const int8_t qc = lv->cls[i];
            if ((int32_t)qc < q_thr) continue;      /* integer reject */

            const float logit = nirdet_deq(qc, lv->cls_zp, lv->cls_scale);
            const float score = nirdet_sigmoid(logit);
            if (score < cfg->score_thresh) continue;

            const float t_cx = nirdet_deq(lv->off[i],          lv->off_zp,  lv->off_scale);
            const float t_cy = nirdet_deq(lv->off[plane + i],  lv->off_zp,  lv->off_scale);
            const float t_w  = nirdet_deq(lv->size[i],         lv->size_zp, lv->size_scale);
            const float t_h  = nirdet_deq(lv->size[plane + i], lv->size_zp, lv->size_scale);

            const float cx = (DECODE_OFFSET_SCALE * nirdet_sigmoid(t_cx)
                              - DECODE_OFFSET_BIAS + (float)col) * st;
            const float cy = (DECODE_OFFSET_SCALE * nirdet_sigmoid(t_cy)
                              - DECODE_OFFSET_BIAS + (float)row) * st;
            const float bw = expf(nirdet_clampf(t_w, REG_LOG_CLAMP_MIN,
                                                REG_LOG_CLAMP_MAX)) * img_w;
            const float bh = expf(nirdet_clampf(t_h, REG_LOG_CLAMP_MIN,
                                                REG_LOG_CLAMP_MAX)) * img_h;

            NirdetBox b;
            b.x1 = cx - 0.5f * bw;
            b.y1 = cy - 0.5f * bh;
            b.x2 = cx + 0.5f * bw;
            b.y2 = cy + 0.5f * bh;

            /* MEMBERSHIP steps 3 then 4, IN THAT ORDER (config.py
             * clamp_and_filter). Testing the PRE-clamp extent admits a box
             * decoded entirely off-canvas: it collapses to zero area at the
             * clamp, has IoU 0 against everything, is therefore
             * unsuppressable by greedy NMS, and burns an output slot. */
            if (b.x1 < 0.f)   b.x1 = 0.f;
            if (b.y1 < 0.f)   b.y1 = 0.f;
            if (b.x2 > img_w) b.x2 = img_w;
            if (b.y2 > img_h) b.y2 = img_h;
            if ((b.x2 - b.x1) <= NIRDET_MIN_BOX_PX) continue;
            if ((b.y2 - b.y1) <= NIRDET_MIN_BOX_PX) continue;

            b.score = score;
            heap_offer(heap, heap_n, cap, &b);
        }
    }
}

/* ---------------------------------------------------------------------- *
 * public entry point
 * ---------------------------------------------------------------------- */

/*
 * Returns the number of boxes written to out[], or -1 on a configuration
 * error.
 *
 * out_cap must be >= NIRDET_MAX_DET. NMS runs in place over the full
 * candidate pool before cfg->max_det is applied, so out[] is the working
 * buffer, not just the result buffer.
 *
 * NOT REENTRANT: static heap here, static suppression buffer in nirdet_nms.
 */
int32_t nirdet_postprocess(const NirdetCfg *cfg, NirdetBox *out,
                           int32_t out_cap)
{
    static NirdetBox heap[NIRDET_MAX_DET];
    int32_t heap_n = 0;

    if (cfg == NULL || out == NULL) return -1;
    if (cfg->n_levels <= 0 || cfg->n_levels > NIRDET_MAX_LEVELS) return -1;
    if (cfg->max_det <= 0 || cfg->max_det > NIRDET_MAX_DET) return -1;
    if (out_cap < NIRDET_MAX_DET) return -1;
    if (cfg->img_h <= 0 || cfg->img_w <= 0) return -1;

    /* The heap holds CANDIDATES, not results. Sizing it at cfg->max_det
     * would apply the cap before suppression (step 6 before step 5). */
    const int32_t cand_cap = NIRDET_MAX_DET;

    for (int32_t l = 0; l < cfg->n_levels; ++l) {
        const NirdetLevelCfg *lv = &cfg->levels[l];
        if (lv->cls == NULL || lv->off == NULL || lv->size == NULL) return -1;
        if (lv->grid_h <= 0 || lv->grid_w <= 0 || lv->stride <= 0) return -1;
        /* A host that fills grid_w/grid_h inconsistently with the stride
         * produces wrong centres and sizes with NO error unless checked. */
        if (lv->grid_w * lv->stride != cfg->img_w) return -1;
        if (lv->grid_h * lv->stride != cfg->img_h) return -1;
        nirdet_decode_level(lv, cfg, heap, &heap_n, cand_cap);
    }

    nirdet_heap_drain_desc(heap, heap_n, out);
    int32_t kept = nirdet_nms(out, heap_n, cfg->iou_thresh);
    return kept > cfg->max_det ? cfg->max_det : kept;
}

/* ---------------------------------------------------------------------- *
 * selftest
 * ---------------------------------------------------------------------- */

#ifdef NIRDET_PP_SELFTEST

#include <assert.h>
#include <stdio.h>

#define ST_H 9
#define ST_W 16
#define ST_STRIDE 32
#define ST_PLANE (ST_H * ST_W)

static int8_t g_cls[ST_PLANE];
static int8_t g_off[2 * ST_PLANE];
static int8_t g_size[2 * ST_PLANE];

/* NOTE: lrintf rounds HALF-TO-EVEN while ORT and ncnn round
 * HALF-AWAY-FROM-ZERO, so a value landing exactly on a .5 boundary
 * quantises one LSB differently from a real exported tensor. Synthetic
 * inputs only. */
static int8_t q_of(float v, float scale, int32_t zp)
{
    float q = v / scale + (float)zp;
    q = q < -128.f ? -128.f : (q > 127.f ? 127.f : q);
    return (int8_t)lrintf(q);
}

static void put_cell(int32_t row, int32_t col, float logit,
                     float t_cx, float t_cy, float t_w, float t_h,
                     float cls_s, int32_t cls_z, float off_s, int32_t off_z,
                     float size_s, int32_t size_z)
{
    int32_t i = row * ST_W + col;
    g_cls[i] = q_of(logit, cls_s, cls_z);
    g_off[i] = q_of(t_cx, off_s, off_z);
    g_off[ST_PLANE + i] = q_of(t_cy, off_s, off_z);
    g_size[i] = q_of(t_w, size_s, size_z);
    g_size[ST_PLANE + i] = q_of(t_h, size_s, size_z);
}

int main(void)
{
    const float cls_s = 0.08f;   const int32_t cls_z = 0;
    const float off_s = 0.05f;   const int32_t off_z = 0;
    const float size_s = 7.0f / 255.0f; const int32_t size_z = -45;

    const int32_t img_h = ST_H * ST_STRIDE;
    const int32_t img_w = ST_W * ST_STRIDE;

    printf("[selftest] contract stamp %s\n", NIRDET_CONTRACT_STAMP);

    for (int32_t i = 0; i < ST_PLANE; ++i) {
        g_cls[i] = q_of(-8.0f, cls_s, cls_z);
        g_off[i] = q_of(0.0f, off_s, off_z);
        g_off[ST_PLANE + i] = q_of(0.0f, off_s, off_z);
        g_size[i] = q_of(REG_LOG_CLAMP_MIN, size_s, size_z);
        g_size[ST_PLANE + i] = q_of(REG_LOG_CLAMP_MIN, size_s, size_z);
    }

    const float lw = logf(100.0f / (float)img_w);
    const float lh = logf(115.0f / (float)img_h);

    put_cell(4, 8, 4.0f, 0.0f, 0.0f, lw, lh,
             cls_s, cls_z, off_s, off_z, size_s, size_z);   /* A strongest  */
    put_cell(4, 9, 2.0f, 0.0f, 0.0f, lw, lh,
             cls_s, cls_z, off_s, off_z, size_s, size_z);   /* B overlaps A */
    put_cell(1, 1, 1.0f, 0.0f, 0.0f, lw, lh,
             cls_s, cls_z, off_s, off_z, size_s, size_z);   /* C far away   */

    NirdetCfg cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.n_levels = 1;
    cfg.img_h = img_h;
    cfg.img_w = img_w;
    cfg.score_thresh = 0.30f;
    cfg.iou_thresh = 0.45f;
    cfg.max_det = 64;
    cfg.levels[0].cls = g_cls;
    cfg.levels[0].off = g_off;
    cfg.levels[0].size = g_size;
    cfg.levels[0].cls_scale = cls_s;   cfg.levels[0].cls_zp = cls_z;
    cfg.levels[0].off_scale = off_s;   cfg.levels[0].off_zp = off_z;
    cfg.levels[0].size_scale = size_s; cfg.levels[0].size_zp = size_z;
    cfg.levels[0].grid_h = ST_H;
    cfg.levels[0].grid_w = ST_W;
    cfg.levels[0].stride = ST_STRIDE;

    NirdetBox out[NIRDET_MAX_DET];
    int32_t n = nirdet_postprocess(&cfg, out, NIRDET_MAX_DET);
    printf("[selftest] nirdet_postprocess -> %d box(es)\n", (int)n);
    assert(n >= 1);

    const float exp_cx_a = (DECODE_OFFSET_SCALE * 0.5f - DECODE_OFFSET_BIAS
                            + 8.0f) * (float)ST_STRIDE;
    const float exp_cx_b = (DECODE_OFFSET_SCALE * 0.5f - DECODE_OFFSET_BIAS
                            + 9.0f) * (float)ST_STRIDE;
    const float exp_cx_c = (DECODE_OFFSET_SCALE * 0.5f - DECODE_OFFSET_BIAS
                            + 1.0f) * (float)ST_STRIDE;
    float cx0 = 0.5f * (out[0].x1 + out[0].x2);
    assert(fabsf(cx0 - exp_cx_a) < 2.0f);
    assert(out[0].score > 0.95f);
    for (int32_t i = 1; i < n; ++i) assert(out[i].score <= out[0].score);
    printf("[selftest] (a) highest-scoring box survived, first  PASS\n");

    int found_b = 0, found_c = 0;
    for (int32_t i = 0; i < n; ++i) {
        float cx = 0.5f * (out[i].x1 + out[i].x2);
        if (fabsf(cx - exp_cx_b) < 2.0f) found_b = 1;
        if (fabsf(cx - exp_cx_c) < 2.0f) found_c = 1;
    }
    assert(!found_b);
    assert(found_c);
    printf("[selftest] (b) overlapping neighbour suppressed    PASS\n");
    printf("[selftest] (c) distant box survived                PASS\n");

    /* (d) MEMBERSHIP ORDER: a box decoded entirely off-canvas (above the
     * top edge) must be dropped at the clamp, not passed to NMS with a
     * negative extent. A horizontal sliver is NOT representable with this
     * test's quantisation grid: size_scale=7/255 saturates the log-size at
     * t=-2.28, so min bw = exp(-2.28)*512 = 52.5px while the most-negative
     * col-0 centre is cx = (2*sigmoid(-6.4)-0.5)*32 = -15.8px -> x2 >= +10px,
     * always on-canvas. The vertical axis repeats the same decode arithmetic
     * with img_h=288: min bh = 29.5px, row-0 cy = -15.9px -> y2 = -1.1px < 0
     * -> clamped extent <= NIRDET_MIN_BOX_PX -> DROPPED.
     * (A pre-clamp extent check would have KEPT this 29.5px box and fed
     * NMS a negative-area candidate — which is what this case pins down.) */
    for (int32_t i = 0; i < ST_PLANE; ++i) g_cls[i] = q_of(-8.0f, cls_s, cls_z);
    put_cell(0, 4, 4.0f, 0.0f, -6.4f, REG_LOG_CLAMP_MIN, REG_LOG_CLAMP_MIN,
             cls_s, cls_z, off_s, off_z, size_s, size_z);
    n = nirdet_postprocess(&cfg, out, NIRDET_MAX_DET);
    printf("[selftest] off-canvas sliver -> %d box(es) (expect 0)\n", (int)n);
    assert(n == 0);
    printf("[selftest] (d) clamp-then-drop order               PASS\n");

    /* (e) HEAP, NOT RASTER TRUNCATION, and max_det applied AFTER NMS.
     * Fill the grid with increasing scores so the best cells are LAST in
     * raster order — the exact case raster truncation got wrong. */
    for (int32_t i = 0; i < ST_PLANE; ++i) {
        g_cls[i] = q_of(0.5f + 0.02f * (float)i, cls_s, cls_z);
        g_off[i] = q_of(0.0f, off_s, off_z);
        g_off[ST_PLANE + i] = q_of(0.0f, off_s, off_z);
        g_size[i] = q_of(lw, size_s, size_z);
        g_size[ST_PLANE + i] = q_of(lh, size_s, size_z);
    }
    cfg.max_det = 8;
    cfg.iou_thresh = 1.01f;          /* disable suppression for this check */
    n = nirdet_postprocess(&cfg, out, NIRDET_MAX_DET);
    printf("[selftest] max_det 8 -> %d box(es), top score %.4f\n",
           (int)n, out[0].score);
    assert(n > 0 && n <= 8);
    {
        float best_logit = 0.5f + 0.02f * (float)(ST_PLANE - 1);
        float best = nirdet_sigmoid(nirdet_deq(q_of(best_logit, cls_s, cls_z),
                                               cls_z, cls_s));
        assert(fabsf(out[0].score - best) < 1e-3f);
    }
    printf("[selftest] (e) heap keeps the strongest, cap after NMS  PASS\n");

    printf("[selftest] ALL PASS\n");
    return 0;
}

#endif /* NIRDET_PP_SELFTEST */
'''


# ---------------------------------------------------------------------------
# render / check
# ---------------------------------------------------------------------------

def render() -> str:
    vals = contract_values()
    stamp = contract_stamp(vals)
    src = _TEMPLATE
    src = src.replace("@@BANNER@@", BANNER)
    src = src.replace("@@STAMP@@", stamp)
    for name in ("DECODE_OFFSET_SCALE", "DECODE_OFFSET_BIAS",
                 "REG_LOG_CLAMP_MIN", "REG_LOG_CLAMP_MAX",
                 "NIRDET_MIN_BOX_PX"):
        src = src.replace(f"@@{name}@@", _cf(vals[name]))
    for name in ("NIRDET_NUM_CLASSES", "NIRDET_MAX_LEVELS", "NIRDET_MAX_DET"):
        src = src.replace(f"@@{name}@@", str(int(vals[name])))
    if "@@" in src:
        leftover = src[src.index("@@"):src.index("@@") + 40]
        raise AssertionError(f"unsubstituted placeholder near: {leftover!r}")
    return src


def check(path: str = C_PATH) -> tuple:
    """-> (ok, human-readable report). Used by test_decode_contract.py T8."""
    want = render()
    if not os.path.isfile(path):
        return False, f"{path} does not exist; run gen_contract_c.py --emit"
    with open(path, "r", encoding="utf-8", newline="") as fh:
        got = fh.read()
    if got == want:
        return True, f"{os.path.basename(path)} matches config.py " \
                     f"(stamp {contract_stamp(contract_values())})"
    diff = list(difflib.unified_diff(
        got.splitlines(True), want.splitlines(True),
        fromfile="on disk", tofile="generated", n=2))
    head = "".join(diff[:60])
    return False, (f"{os.path.basename(path)} is STALE relative to config.py. "
                   f"Run: python gen_contract_c.py --emit\n{head}")


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--emit", action="store_true", help="write nirdet_pp.c")
    g.add_argument("--check", action="store_true", help="exit 1 if stale")
    g.add_argument("--print", dest="to_stdout", action="store_true")
    ap.add_argument("--out", default=C_PATH)
    args = ap.parse_args(argv)

    if args.to_stdout:
        sys.stdout.write(render())
        return 0
    if args.check:
        ok, report = check(args.out)
        print(("[gen] " if ok else "[gen] FAIL ") + report)
        return 0 if ok else 1

    src = render()
    # newline="" so the file is byte-identical on Windows and Linux; --check
    # compares bytes and a CRLF translation would fail the gate on one OS.
    with open(args.out, "w", encoding="utf-8", newline="") as fh:
        fh.write(src)
    print(f"[gen] wrote {args.out} ({len(src)} bytes, "
          f"stamp {contract_stamp(contract_values())})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
