/* main.c — NIRDet-Forge inference loop for STM32N6570-DK
 * =========================================================
 * Uses the ST AI (stai_*) API generated by stedgeai with --st-neural-art.
 *
 * Output buffer order (from stai_nirdet.h STAI_NIRDET_OUT_NAMES):
 *   [0] Quantize_221 = cls8   int8 1x1x36x64  2304B  scale=0.05507 zp=81
 *   [1] Quantize_229 = off8   int8 1x2x36x64  4608B  scale=0.18284 zp=2
 *   [2] Quantize_227 = size8  int8 1x2x36x64  4608B  scale=0.01787 zp=119
 *   [3] Quantize_200 = cls16  int8 1x1x18x32   576B  scale=0.04411 zp=75
 *   [4] Quantize_208 = off16  int8 1x2x18x32  1152B  scale=0.14667 zp=-4
 *   [5] Quantize_206 = size16 int8 1x2x18x32  1152B  scale=0.01602 zp=124
 *   [6] Quantize_152 = cls32  int8 1x1x9x16    144B  scale=0.02662 zp=127
 *   [7] Quantize_160 = off32  int8 1x2x9x16    288B  scale=0.03285 zp=43
 *   [8] Quantize_158 = size32 int8 1x2x9x16    288B  scale=0.01548 zp=127
 */

#include <stdint.h>
#include <string.h>

#include "stai_nirdet.h"   /* stai_nirdet_init/run/set_inputs/set_outputs */
#include "nirdet_pp.h"     /* NirdetCfg, NirdetBox, nirdet_postprocess()  */

/* ---------------------------------------------------------------------- *
 * Canvas geometry — must match config.py
 * ---------------------------------------------------------------------- */
#define IMG_H   288
#define IMG_W   512

/* ---------------------------------------------------------------------- *
 * Detection thresholds
 * ---------------------------------------------------------------------- */
#define SCORE_THRESH  0.430f
#define IOU_THRESH    0.45f
#define MAX_DET       300      /* <= NIRDET_MAX_DET */

#include "arm_cmse.h"

/* Dummy CMSE entry required by --cmse-implib linker flag */
__attribute__((cmse_nonsecure_entry))
void cmse_entry_dummy(void) {}

/* ---------------------------------------------------------------------- *
 * Network context
 * stai_network is 'unsigned char' in this build; the API takes stai_network*
 * ---------------------------------------------------------------------- */
static stai_network g_network;

/* ---------------------------------------------------------------------- *
 * Input buffer: int8, 1x1x288x512 = 147456 bytes, alignment 32
 * ---------------------------------------------------------------------- */
static int8_t input_buf[STAI_NIRDET_IN_1_SIZE_BYTES]
    __attribute__((aligned(32)));

/* ---------------------------------------------------------------------- *
 * Output buffers — 9 blobs, INT8, alignment 32 each
 * ---------------------------------------------------------------------- */
static int8_t cls8  [STAI_NIRDET_OUT_1_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t off8  [STAI_NIRDET_OUT_2_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t size8 [STAI_NIRDET_OUT_3_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t cls16 [STAI_NIRDET_OUT_4_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t off16 [STAI_NIRDET_OUT_5_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t size16[STAI_NIRDET_OUT_6_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t cls32 [STAI_NIRDET_OUT_7_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t off32 [STAI_NIRDET_OUT_8_SIZE_BYTES] __attribute__((aligned(32)));
static int8_t size32[STAI_NIRDET_OUT_9_SIZE_BYTES] __attribute__((aligned(32)));

/* Pointer arrays passed to stai_nirdet_set_inputs / set_outputs */
static stai_ptr inputs[STAI_NIRDET_IN_NUM]   = { (stai_ptr)input_buf };
static stai_ptr outputs[STAI_NIRDET_OUT_NUM] = {
    (stai_ptr)cls8,  (stai_ptr)off8,  (stai_ptr)size8,
    (stai_ptr)cls16, (stai_ptr)off16, (stai_ptr)size16,
    (stai_ptr)cls32, (stai_ptr)off32, (stai_ptr)size32,
};

/* ---------------------------------------------------------------------- *
 * Post-processor config
 * ---------------------------------------------------------------------- */
static const NirdetCfg g_cfg = {
    .levels = {
        /* stride-8 */
        {
            .cls = cls8,  .off = off8,  .size = size8,
            .cls_scale  = 0.0550706312f, .cls_zp  = 81,
            .off_scale  = 0.1828420013f, .off_zp  = 2,
            .size_scale = 0.0178692229f, .size_zp = 119,
            .grid_h = 36, .grid_w = 64, .stride = 8,
        },
        /* stride-16 */
        {
            .cls = cls16, .off = off16, .size = size16,
            .cls_scale  = 0.0441131219f, .cls_zp  = 75,
            .off_scale  = 0.1466677934f, .off_zp  = -4,
            .size_scale = 0.0160245188f, .size_zp = 124,
            .grid_h = 18, .grid_w = 32, .stride = 16,
        },
        /* stride-32 */
        {
            .cls = cls32, .off = off32, .size = size32,
            .cls_scale  = 0.0266222004f, .cls_zp  = 127,
            .off_scale  = 0.0328494124f, .off_zp  = 43,
            .size_scale = 0.0154807130f, .size_zp = 127,
            .grid_h = 9,  .grid_w = 16, .stride = 32,
        },
    },
    .n_levels     = 3,
    .img_h        = IMG_H,
    .img_w        = IMG_W,
    .score_thresh = SCORE_THRESH,
    .iou_thresh   = IOU_THRESH,
    .max_det      = MAX_DET,
};

/* Detection results */
static NirdetBox detections[MAX_DET];

/* ---------------------------------------------------------------------- *
 * main
 * ---------------------------------------------------------------------- */
int main(void)
{
    /* 1. Initialise the Neural-ART runtime and network */
    stai_nirdet_init(&g_network);

    /* 2. Bind input and output buffers (done once — they are static) */
    stai_nirdet_set_inputs (&g_network, inputs,  STAI_NIRDET_IN_NUM);
    stai_nirdet_set_outputs(&g_network, outputs, STAI_NIRDET_OUT_NUM);

    /* 3. Zero the input — replace with real camera frame feed */
    memset(input_buf, 0, sizeof(input_buf));

    while (1)
    {
        /* 3a. Fill input_buf with your pre-processed frame here
         *     (CLAHE + letterbox + convert to int8 with scale 1/255, zp=-128) */

        /* 4. Run NPU inference (synchronous) */
        stai_nirdet_run(&g_network, STAI_MODE_SYNC);

        /* 5. Post-process: decode INT8 blobs -> NMS -> boxes */
        int32_t n_det = nirdet_postprocess(&g_cfg, detections, MAX_DET);

        /* 6. Use results — n_det boxes in detections[0..n_det-1]
         *    Each: x1, y1, x2, y2 in canvas pixels, score.
         *    TODO: drive GPIO, UART, display output here. */
        (void)n_det;
    }
}
