/*
 * nirdet_pp.c — NIRDet-Forge post-processor for STM32N6 / Cortex-M55
 * ==================================================================
 * GENERATED BY gen_contract_c.py FROM config.py -- DO NOT EDIT. Run: python gen_contract_c.py --emit
 *
 * Contract stamp: ed9bd4eb8e4f1922
 */

#include <math.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "nirdet_pp.h"

/* ---------------------------------------------------------------------- *
 * DECODE CONTRACT — rendered from config.py. Edit config.py, then re-emit.
 * ---------------------------------------------------------------------- */
#define NIRDET_CONTRACT_STAMP "ed9bd4eb8e4f1922"

#define DECODE_OFFSET_SCALE  2.0f
#define DECODE_OFFSET_BIAS   0.5f
#define REG_LOG_CLAMP_MIN    -6.0f
#define REG_LOG_CLAMP_MAX    1.0f
#define NIRDET_MIN_BOX_PX    1.0f

/* C99 portability: _Static_assert is C11. */
#if !defined(__STDC_VERSION__) || (__STDC_VERSION__ < 201112L)
#define _Static_assert(cond, msg) \
    typedef char nirdet_static_assert_##__LINE__[(cond) ? 1 : -1]
#endif

_Static_assert(NIRDET_NUM_CLASSES == 1,
    "this post-processor is single-class; update nirdet_decode_level "
    "to handle multiple classes before increasing NIRDET_NUM_CLASSES");
_Static_assert(NIRDET_MAX_LEVELS >= 1 && NIRDET_MAX_LEVELS <= 8,
    "NIRDET_MAX_LEVELS is a static capacity for NirdetCfg.levels[]");

/* ---------------------------------------------------------------------- *
 * scalar helpers
 * ---------------------------------------------------------------------- */

static inline float nirdet_sigmoid(float x)
{
    if (x >= 0.0f) {
        return 1.0f / (1.0f + expf(-x));
    }
    const float e = expf(x);
    return e / (1.0f + e);
}

static inline float nirdet_clampf(float v, float lo, float hi)
{
    return v < lo ? lo : (v > hi ? hi : v);
}

static inline float nirdet_deq(int8_t q, int32_t zp, float scale)
{
    return ((float)((int32_t)q - zp)) * scale;
}

static int32_t nirdet_int_thresh(float score_thresh, float scale, int32_t zp)
{
    float t = nirdet_clampf(score_thresh, 1e-6f, 1.0f - 1e-6f);
    float logit = logf(t / (1.0f - t));
    float q = (float)zp + logit / (scale > 0.f ? scale : 1e-9f);
    float c = ceilf(q);
    if (c < -128.f) c = -128.f;
    if (c >  127.f) c =  127.f;
    return (int32_t)c;
}

/* ---------------------------------------------------------------------- *
 * fixed-capacity min-heap on .score
 * ---------------------------------------------------------------------- */

static inline void heap_swap(NirdetBox *a, NirdetBox *b)
{
    NirdetBox t = *a; *a = *b; *b = t;
}

static inline void heap_sift_down(NirdetBox *h, int32_t n, int32_t i)
{
    for (;;) {
        int32_t l = 2 * i + 1, r = l + 1, m = i;
        if (l < n && h[l].score < h[m].score) m = l;
        if (r < n && h[r].score < h[m].score) m = r;
        if (m == i) return;
        heap_swap(&h[i], &h[m]);
        i = m;
    }
}

static inline void heap_sift_up(NirdetBox *h, int32_t i)
{
    while (i > 0) {
        int32_t p = (i - 1) / 2;
        if (h[p].score <= h[i].score) return;
        heap_swap(&h[p], &h[i]);
        i = p;
    }
}

static inline void heap_push(NirdetBox *h, int32_t *n, const NirdetBox *b)
{
    h[*n] = *b;
    heap_sift_up(h, *n);
    (*n)++;
}

static inline void heap_pop(NirdetBox *h, int32_t *n)
{
    if (*n <= 0) return;
    (*n)--;
    h[0] = h[*n];
    heap_sift_down(h, *n, 0);
}

static inline void heap_offer(NirdetBox *h, int32_t *n, int32_t cap,
                              const NirdetBox *b)
{
    if (*n < cap) {
        heap_push(h, n, b);
    } else if (cap > 0 && b->score > h[0].score) {
        h[0] = *b;
        heap_sift_down(h, *n, 0);
    }
}

/* ---------------------------------------------------------------------- *
 * IoU + greedy NMS (no allocation)
 * ---------------------------------------------------------------------- */

static float nirdet_iou(const NirdetBox *a, const NirdetBox *b)
{
    float x1 = a->x1 > b->x1 ? a->x1 : b->x1;
    float y1 = a->y1 > b->y1 ? a->y1 : b->y1;
    float x2 = a->x2 < b->x2 ? a->x2 : b->x2;
    float y2 = a->y2 < b->y2 ? a->y2 : b->y2;
    float iw = x2 - x1, ih = y2 - y1;
    if (iw <= 0.f || ih <= 0.f) return 0.f;
    float inter = iw * ih;
    float aa = (a->x2 - a->x1) * (a->y2 - a->y1);
    float ab = (b->x2 - b->x1) * (b->y2 - b->y1);
    float uni = aa + ab - inter;
    return uni > 0.f ? inter / uni : 0.f;
}

static void nirdet_heap_drain_desc(NirdetBox *h, int32_t n, NirdetBox *out)
{
    int32_t i = n;
    while (i > 0) {
        NirdetBox top = h[0];
        heap_pop(h, &i);
        out[i] = top;
    }
}

static int32_t nirdet_nms(NirdetBox *boxes, int32_t n, float iou_thresh)
{
    static uint8_t suppressed[NIRDET_MAX_DET];
    if (n <= 0) return 0;
    if (n > NIRDET_MAX_DET) n = NIRDET_MAX_DET;
    memset(suppressed, 0, (size_t)n);

    int32_t kept = 0;
    for (int32_t i = 0; i < n; ++i) {
        if (suppressed[i]) continue;
        for (int32_t j = i + 1; j < n; ++j) {
            if (suppressed[j]) continue;
            if (nirdet_iou(&boxes[i], &boxes[j]) > iou_thresh)
                suppressed[j] = 1u;
        }
        boxes[kept++] = boxes[i];
    }
    return kept;
}

/* ---------------------------------------------------------------------- *
 * one level -> heap
 * ---------------------------------------------------------------------- */

static void nirdet_decode_level(const NirdetLevelCfg *lv, const NirdetCfg *cfg,
                                NirdetBox *heap, int32_t *heap_n, int32_t cap)
{
    const int32_t H = lv->grid_h, W = lv->grid_w;
    const int32_t plane = H * W;
    const int32_t q_thr = nirdet_int_thresh(cfg->score_thresh,
                                            lv->cls_scale, lv->cls_zp);
    const float img_w = (float)cfg->img_w;
    const float img_h = (float)cfg->img_h;
    const float st = (float)lv->stride;

    for (int32_t row = 0; row < H; ++row) {
        for (int32_t col = 0; col < W; ++col) {
            const int32_t i = row * W + col;
            const int8_t qc = lv->cls[i];
            if ((int32_t)qc < q_thr) continue;

            const float logit = nirdet_deq(qc, lv->cls_zp, lv->cls_scale);
            const float score = nirdet_sigmoid(logit);
            if (score < cfg->score_thresh) continue;

            const float t_cx = nirdet_deq(lv->off[i],          lv->off_zp,  lv->off_scale);
            const float t_cy = nirdet_deq(lv->off[plane + i],  lv->off_zp,  lv->off_scale);
            const float t_w  = nirdet_deq(lv->size[i],         lv->size_zp, lv->size_scale);
            const float t_h  = nirdet_deq(lv->size[plane + i], lv->size_zp, lv->size_scale);

            const float cx = (DECODE_OFFSET_SCALE * nirdet_sigmoid(t_cx)
                              - DECODE_OFFSET_BIAS + (float)col) * st;
            const float cy = (DECODE_OFFSET_SCALE * nirdet_sigmoid(t_cy)
                              - DECODE_OFFSET_BIAS + (float)row) * st;
            const float bw = expf(nirdet_clampf(t_w, REG_LOG_CLAMP_MIN,
                                                REG_LOG_CLAMP_MAX)) * img_w;
            const float bh = expf(nirdet_clampf(t_h, REG_LOG_CLAMP_MIN,
                                                REG_LOG_CLAMP_MAX)) * img_h;

            NirdetBox b;
            b.x1 = cx - 0.5f * bw;
            b.y1 = cy - 0.5f * bh;
            b.x2 = cx + 0.5f * bw;
            b.y2 = cy + 0.5f * bh;

            if (b.x1 < 0.f)   b.x1 = 0.f;
            if (b.y1 < 0.f)   b.y1 = 0.f;
            if (b.x2 > img_w) b.x2 = img_w;
            if (b.y2 > img_h) b.y2 = img_h;
            if ((b.x2 - b.x1) <= NIRDET_MIN_BOX_PX) continue;
            if ((b.y2 - b.y1) <= NIRDET_MIN_BOX_PX) continue;

            b.score = score;
            heap_offer(heap, heap_n, cap, &b);
        }
    }
}

/* ---------------------------------------------------------------------- *
 * public entry point
 * ---------------------------------------------------------------------- */

int32_t nirdet_postprocess(const NirdetCfg *cfg, NirdetBox *out,
                           int32_t out_cap)
{
    static NirdetBox heap[NIRDET_MAX_DET];
    int32_t heap_n = 0;

    if (cfg == NULL || out == NULL) return -1;
    if (cfg->n_levels <= 0 || cfg->n_levels > NIRDET_MAX_LEVELS) return -1;
    if (cfg->max_det <= 0 || cfg->max_det > NIRDET_MAX_DET) return -1;
    if (out_cap < NIRDET_MAX_DET) return -1;
    if (cfg->img_h <= 0 || cfg->img_w <= 0) return -1;

    const int32_t cand_cap = NIRDET_MAX_DET;

    for (int32_t l = 0; l < cfg->n_levels; ++l) {
        const NirdetLevelCfg *lv = &cfg->levels[l];
        if (lv->cls == NULL || lv->off == NULL || lv->size == NULL) return -1;
        if (lv->grid_h <= 0 || lv->grid_w <= 0 || lv->stride <= 0) return -1;
        if (lv->grid_w * lv->stride != cfg->img_w) return -1;
        if (lv->grid_h * lv->stride != cfg->img_h) return -1;
        nirdet_decode_level(lv, cfg, heap, &heap_n, cand_cap);
    }

    nirdet_heap_drain_desc(heap, heap_n, out);
    int32_t kept = nirdet_nms(out, heap_n, cfg->iou_thresh);
    return kept > cfg->max_det ? cfg->max_det : kept;
}

/* ---------------------------------------------------------------------- *
 * selftest
 * ---------------------------------------------------------------------- */

#ifdef NIRDET_PP_SELFTEST

#include <assert.h>
#include <stdio.h>

#define ST_H 9
#define ST_W 16
#define ST_STRIDE 32
#define ST_PLANE (ST_H * ST_W)

static int8_t g_cls[ST_PLANE];
static int8_t g_off[2 * ST_PLANE];
static int8_t g_size[2 * ST_PLANE];

static int8_t q_of(float v, float scale, int32_t zp)
{
    float q = v / scale + (float)zp;
    q = q < -128.f ? -128.f : (q > 127.f ? 127.f : q);
    return (int8_t)lrintf(q);
}

static void put_cell(int32_t row, int32_t col, float logit,
                     float t_cx, float t_cy, float t_w, float t_h,
                     float cls_s, int32_t cls_z, float off_s, int32_t off_z,
                     float size_s, int32_t size_z)
{
    int32_t i = row * ST_W + col;
    g_cls[i] = q_of(logit, cls_s, cls_z);
    g_off[i] = q_of(t_cx, off_s, off_z);
    g_off[ST_PLANE + i] = q_of(t_cy, off_s, off_z);
    g_size[i] = q_of(t_w, size_s, size_z);
    g_size[ST_PLANE + i] = q_of(t_h, size_s, size_z);
}

int main(void)
{
    const float cls_s = 0.08f;   const int32_t cls_z = 0;
    const float off_s = 0.05f;   const int32_t off_z = 0;
    const float size_s = 7.0f / 255.0f; const int32_t size_z = -45;

    const int32_t img_h = ST_H * ST_STRIDE;
    const int32_t img_w = ST_W * ST_STRIDE;

    printf("[selftest] contract stamp %s\n", NIRDET_CONTRACT_STAMP);

    for (int32_t i = 0; i < ST_PLANE; ++i) {
        g_cls[i] = q_of(-8.0f, cls_s, cls_z);
        g_off[i] = q_of(0.0f, off_s, off_z);
        g_off[ST_PLANE + i] = q_of(0.0f, off_s, off_z);
        g_size[i] = q_of(REG_LOG_CLAMP_MIN, size_s, size_z);
        g_size[ST_PLANE + i] = q_of(REG_LOG_CLAMP_MIN, size_s, size_z);
    }

    const float lw = logf(100.0f / (float)img_w);
    const float lh = logf(115.0f / (float)img_h);

    put_cell(4, 8, 4.0f, 0.0f, 0.0f, lw, lh,
             cls_s, cls_z, off_s, off_z, size_s, size_z);
    put_cell(4, 9, 2.0f, 0.0f, 0.0f, lw, lh,
             cls_s, cls_z, off_s, off_z, size_s, size_z);
    put_cell(1, 1, 1.0f, 0.0f, 0.0f, lw, lh,
             cls_s, cls_z, off_s, off_z, size_s, size_z);

    NirdetCfg cfg;
    memset(&cfg, 0, sizeof(cfg));
    cfg.n_levels = 1;
    cfg.img_h = img_h;
    cfg.img_w = img_w;
    cfg.score_thresh = 0.30f;
    cfg.iou_thresh = 0.45f;
    cfg.max_det = 64;
    cfg.levels[0].cls = g_cls;
    cfg.levels[0].off = g_off;
    cfg.levels[0].size = g_size;
    cfg.levels[0].cls_scale = cls_s;   cfg.levels[0].cls_zp = cls_z;
    cfg.levels[0].off_scale = off_s;   cfg.levels[0].off_zp = off_z;
    cfg.levels[0].size_scale = size_s; cfg.levels[0].size_zp = size_z;
    cfg.levels[0].grid_h = ST_H;
    cfg.levels[0].grid_w = ST_W;
    cfg.levels[0].stride = ST_STRIDE;

    NirdetBox out[NIRDET_MAX_DET];
    int32_t n = nirdet_postprocess(&cfg, out, NIRDET_MAX_DET);
    printf("[selftest] nirdet_postprocess -> %d box(es)\n", (int)n);
    assert(n >= 1);

    const float exp_cx_a = (DECODE_OFFSET_SCALE * 0.5f - DECODE_OFFSET_BIAS + 8.0f) * (float)ST_STRIDE;
    const float exp_cx_b = (DECODE_OFFSET_SCALE * 0.5f - DECODE_OFFSET_BIAS + 9.0f) * (float)ST_STRIDE;
    const float exp_cx_c = (DECODE_OFFSET_SCALE * 0.5f - DECODE_OFFSET_BIAS + 1.0f) * (float)ST_STRIDE;
    float cx0 = 0.5f * (out[0].x1 + out[0].x2);
    assert(fabsf(cx0 - exp_cx_a) < 2.0f);
    assert(out[0].score > 0.95f);
    for (int32_t i = 1; i < n; ++i) assert(out[i].score <= out[0].score);
    printf("[selftest] (a) highest-scoring box survived, first  PASS\n");

    int found_b = 0, found_c = 0;
    for (int32_t i = 0; i < n; ++i) {
        float cx = 0.5f * (out[i].x1 + out[i].x2);
        if (fabsf(cx - exp_cx_b) < 2.0f) found_b = 1;
        if (fabsf(cx - exp_cx_c) < 2.0f) found_c = 1;
    }
    assert(!found_b);
    assert(found_c);
    printf("[selftest] (b) overlapping neighbour suppressed    PASS\n");
    printf("[selftest] (c) distant box survived                PASS\n");

    for (int32_t i = 0; i < ST_PLANE; ++i) g_cls[i] = q_of(-8.0f, cls_s, cls_z);
    put_cell(0, 4, 4.0f, 0.0f, -6.4f, REG_LOG_CLAMP_MIN, REG_LOG_CLAMP_MIN,
             cls_s, cls_z, off_s, off_z, size_s, size_z);
    n = nirdet_postprocess(&cfg, out, NIRDET_MAX_DET);
    printf("[selftest] off-canvas sliver -> %d box(es) (expect 0)\n", (int)n);
    assert(n == 0);
    printf("[selftest] (d) clamp-then-drop order               PASS\n");

    for (int32_t i = 0; i < ST_PLANE; ++i) {
        g_cls[i] = q_of(0.5f + 0.02f * (float)i, cls_s, cls_z);
        g_off[i] = q_of(0.0f, off_s, off_z);
        g_off[ST_PLANE + i] = q_of(0.0f, off_s, off_z);
        g_size[i] = q_of(lw, size_s, size_z);
        g_size[ST_PLANE + i] = q_of(lh, size_s, size_z);
    }
    cfg.max_det = 8;
    cfg.iou_thresh = 1.01f;
    n = nirdet_postprocess(&cfg, out, NIRDET_MAX_DET);
    printf("[selftest] max_det 8 -> %d box(es), top score %.4f\n",
           (int)n, out[0].score);
    assert(n > 0 && n <= 8);
    {
        float best_logit = 0.5f + 0.02f * (float)(ST_PLANE - 1);
        float best = nirdet_sigmoid(nirdet_deq(q_of(best_logit, cls_s, cls_z),
                                               cls_z, cls_s));
        assert(fabsf(out[0].score - best) < 1e-3f);
    }
    printf("[selftest] (e) heap keeps the strongest, cap after NMS  PASS\n");
    printf("[selftest] ALL PASS\n");
    return 0;
}

#endif /* NIRDET_PP_SELFTEST */
